# Nama aplikasi
app = "aplikasimonitoringskripsi"

# Definisi server dan jalur
[[services]]
  internal_port = 8080
  protocol = "tcp"

  # Konfigurasi HTTP
  [[services.ports]]
    handlers = ["http"]
    port = 80

# Lokasi data center yang dipilih
[[deployments]]
  regions = ["sfo"]
